DEVICE          : cuda            # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'logs/YESeg-logs'          # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : MGFNet                                           # name of the model you are using
  BACKBONE      : Res101_HRw48                                                 # model variant
  PRETRAINED    : True              # backbone model's weight

DATASET:
  NAME          : YESeg_OPT_SAR                                        # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '\datasets\DATA'                                   # dataset root path
  IGNORE_LABEL  : 255

TRAIN:
  IMAGE_SIZE    : [256, 256]    # training image size in (h, w)
  NUM_WORKERS   : 4              # number of workers used in data loading
  BATCH_SIZE    : 4               # batch size used to train
  EPOCHS        : 100            # number of epochs to train
  EVAL_INTERVAL : 1              # evaluation interval during training
  AMP           : false           # use AMP in training
  DP            : false           # use DP in training
  DDP           : false            # use DDP training

LOSS:
  NAME          : Mixloss          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0005           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer

SCHEDULER:
  NAME          : warmupcosinelr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'logs\YESeg-logs\MGFNet_Res101_HRw48_YESeg_OPT_SAR.pth'     # trained model file path
  IMAGE_SIZE    : [256, 256]                            # evaluation image size in (h, w)
